# Site settings
title: Paling - Software
description: > # this means to ignore newlines until "baseurl:"
url: "https://software.bakku.dev"
author: Copyright &copy; Christian Paling
lang: de_DE

markdown: kramdown
sass:
  style: compressed
exclude:
  - .idea
